### ISSUE TITLE
Jquery v1.9+ incompatibility

### ISSUE THREAD

**Issue by mehrizi** [1saeedsalehi/Persian-DatePicker#1]
Great Plugin, I am using it for a while. 
As of jQuery 1.9 they have removed $.browser() and that causes error when the datepicker wants to open.
Of-course I overcame this problem using some hacks suggested by jquery Migrate and I am currently using the plugin on latest jQuery version but as I think doing the actual fix should not take much I am leaving this here.

**Comment by 1saeedsalehi** [comment]
which version of persian date picker  do you use ?

**Comment by mehrizi** [comment]
Sorry for late reply, I was on move.
In the header it says:
jQuery UI Datepicker 1.8.14
Which I believe you made it on top of the base jQueryUI Datepicker.
In anyway do u have any plans to update in here the repo?

Thanks
